name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile.kayenta
          push: true
          tags: |
            ghcr.io/gempesaw/kayenta-quickstart:${{ github.commit_sha }}
            ghcr.io/gempesaw/kayenta-quickstart:latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile.referee
          push: true
          tags: |
            ghcr.io/gempesaw/referee-quickstart:${{ github.commit_sha }}
            ghcr.io/gempesaw/referee-quickstart:latest
